---
beet_domain: "silverstripe.local"
beet_root: "{{ beet_base }}/docroot"
role_path: "{{ beet_home }}/provisioning/ansible/roles/beetboxvm.silverstripe"

beet_project: silverstripe
ss_create_project: yes
ss_install_site: yes
ss_account_name: admin
ss_account_pass: admin
